baseURL = 'https://spyke.space/'
locale = 'en-us'
title = 'Spyke.space'
theme= 'hugo-theme-stack'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 20

[[menu.main]]
name = "Library"
url = "/page/library/"
weight = 30

[params.sidebar]
emoji = "💎"
subtitle = "Field notes, observations, and traces."
avatar = "img/avatar.png"

[params.widgets]
homepage = [
    { type = "archives", params = { limit = 12 } },
    { type = "tag-cloud", params = { limit = 25 } },
]

page = [{ type = "toc" }]