baseURL = 'https://spyke.space/'
locale = 'en-us'
title = 'Field Notes'
theme= 'hugo-theme-stack'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 20

[params.sidebar]
emoji = "💎"
subtitle = "Signals and traces gathered along the way."
avatar = "/img/avatar.png"

[params.widgets]
homepage = [
    { type = "archives", params = { limit = 12 } },
    { type = "tag-cloud", params = { limit = 25 } },
]

page = [{ type = "toc" }]